version: '2'

services:

  redmine-data:
    image: busybox
    volumes:
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/tmp:/usr/src/redmine/tmp
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      - ./redmine/files:/usr/src/redmine/files

  redmine:
    image: redmine
    ports:
      - 8804:3000
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: RedminePassword
    #volumes:
    #  - ./redmine/log:/usr/src/redmine/log
    #  - ./redmine/plugins:/usr/src/redmine/plugins
    #  - ./redmine/tmp:/usr/src/redmine/tmp
    #  - ./redmine/themes:/usr/src/redmine/public/themes
    volumes_from:
      - redmine-data
    depends_on:
      - mariadb
    restart: always

  mariadb-data:
    image: busybox
    volumes:
      - /var/lib/mysql

  mariadb:
    image: mariadb
    #build: Dockerfile.mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: RedminePassword
      MYSQL_DATABASE: redmine
    #volumes:
    #  - ./mariadb:/var/lib/mysql
    volumes_from:
      - mariadb-data
    restart: always
