version: '2'

services:

  redmine-data:
    image: busybox
    volumes:
      - ./redmine/files:/usr/src/redmine/files
      - ./redmine/log:/usr/src/redmine/log
      - ./redmine/plugins:/usr/src/redmine/plugins
      - ./redmine/themes:/usr/src/redmine/public/themes
      #- ./redmine/tmp:/usr/src/redmine/tmp

  redmine:
    depends_on:
      - redmine-data
      - mariadb
    image: redmine:4.0.3
    ports:
      - "${WP_PORT}:3000"
    environment:
      REDMINE_DB_MYSQL: mariadb
      REDMINE_DB_PASSWORD: RedminePassword
    volumes_from:
      - redmine-data
    depends_on:
      - mariadb

  mariadb-data:
    image: busybox
    volumes:
      - /var/lib/mysql

  mariadb:
    depends_on:
      - mariadb-data
    image: mariadb
    #build: Dockerfile.mariadb
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: RedminePassword
      MYSQL_DATABASE: redmine
    volumes_from:
      - mariadb-data
